### ISSUE TITLE
Implémentation du CI

### ISSUE THREAD

**Issue by HakumenNC** [adriens/emploi-nc-app#27]
Via Github Actions.
Voir https://github.com/marketplace/actions/flutter-action

Edit :
- Gérer l'implémentation de la clé RapidAPI avec la création du fichier `app_config.dart`
- La signature du bundle (ou non?) : modification `gradle.build`, etc.

**Comment by adriens** [comment]
Oupe, jy'a eu de la maintenance sur cette action récemment par rapport à la gestion de la version du SDK  justement

**Comment by adriens** [comment]
Cf le ticket dont je te parlais hier : https://github.com/flutter/flutter-intellij/issues/3807

**Comment by HakumenNC** [comment]
Point avancée :
* Action BUILD : subosito/flutter-action (https://github.com/subosito/flutter-action)
* Action Upload vers AWS S3 : jakejarvis/s3-sync-action (https://github.com/jakejarvis/s3-sync-action)
  * En cours.. (droits S3 à mettre d’équerre reader/uploader)
```yml
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
        AWS_REGION: 'ap-southeast-2'
        SOURCE_DIR: 'build/app/outputs/apk/debug'
        DEST_DIR: 'dev/flutter-apps/emploi-nc'
```
